name: Deploy Frontend

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  deploy:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Deploy
        run: |

          mkdir -p /var/www/Tradin/Frontend

          rsync -av --delete \
            --exclude ".git" \
            --exclude ".github" \
            ./ /var/www/Tradin/Frontend/

          cd /var/www/Tradin/Frontend

          docker compose down || true

          docker compose up -d --build
